
queue_test: ../libraries/queue.c ./queue-test.c
	gcc -o ../build/queue-test $^

array_test: ../libraries/array.c ./array-test.c
	gcc -o ../build/array-test $^

run_queue_test:
	../build/queue-test

run_array_test:
	../build/array-test
