-- Should be OK


--[[]]--[[ahojkyneee a da das d

dasdas]]require --[[]]--[[ahojkyneee a da das d

dasdas]]"ifj21"
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]main() --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]string
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]return --[[]]--[[ahojkyneee a da das d

dasdas]]"Hello --[[]]--[[ahojkyneee a da das d

dasdas]]World!"
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]