-- Program 2: Vypocet faktorialu (rekurzivne)


--[[]]--[[ahojkyneee a da das d

dasdas]]require --[[]]--[[ahojkyneee a da das d

dasdas]]"ifj21"
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]factorial(n --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer) --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]local --[[]]--[[ahojkyneee a da das d

dasdas]]n1 --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]n --[[]]--[[ahojkyneee a da das d

dasdas]]- --[[]]--[[ahojkyneee a da das d

dasdas]]1
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]if --[[]]--[[ahojkyneee a da das d

dasdas]]n --[[]]--[[ahojkyneee a da das d

dasdas]]< --[[]]--[[ahojkyneee a da das d

dasdas]]2 --[[]]--[[ahojkyneee a da das d

dasdas]]then
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]return --[[]]--[[ahojkyneee a da das d

dasdas]]1
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]else
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]local --[[]]--[[ahojkyneee a da das d

dasdas]]tmp --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]factorial(n1)
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]return --[[]]--[[ahojkyneee a da das d

dasdas]]n --[[]]--[[ahojkyneee a da das d

dasdas]]* --[[]]--[[ahojkyneee a da das d

dasdas]]tmp
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]main()
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]write("Zadejte --[[]]--[[ahojkyneee a da das d

dasdas]]cislo --[[]]--[[ahojkyneee a da das d

dasdas]]pro --[[]]--[[ahojkyneee a da das d

dasdas]]vypocet --[[]]--[[ahojkyneee a da das d

dasdas]]faktorialu: --[[]]--[[ahojkyneee a da das d

dasdas]]")
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]local --[[]]--[[ahojkyneee a da das d

dasdas]]a --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]readi()
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]if --[[]]--[[ahojkyneee a da das d

dasdas]]a --[[]]--[[ahojkyneee a da das d

dasdas]]~= --[[]]--[[ahojkyneee a da das d

dasdas]]nil --[[]]--[[ahojkyneee a da das d

dasdas]]then
--[[]]--[[ahojkyneee a da das d

dasdas]]	if --[[]]--[[ahojkyneee a da das d

dasdas]]a --[[]]--[[ahojkyneee a da das d

dasdas]]< --[[]]--[[ahojkyneee a da das d

dasdas]]0 --[[]]--[[ahojkyneee a da das d

dasdas]]then
--[[]]--[[ahojkyneee a da das d

dasdas]]		write("Faktorial --[[]]--[[ahojkyneee a da das d

dasdas]]nejde --[[]]--[[ahojkyneee a da das d

dasdas]]spocitat!", --[[]]--[[ahojkyneee a da das d

dasdas]]"\n")
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]	else
--[[]]--[[ahojkyneee a da das d

dasdas]]		local --[[]]--[[ahojkyneee a da das d

dasdas]]vysl --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]factorial(a)
--[[]]--[[ahojkyneee a da das d

dasdas]]		write("Vysledek --[[]]--[[ahojkyneee a da das d

dasdas]]je --[[]]--[[ahojkyneee a da das d

dasdas]]", --[[]]--[[ahojkyneee a da das d

dasdas]]vysl, --[[]]--[[ahojkyneee a da das d

dasdas]]"\n")
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]else
--[[]]--[[ahojkyneee a da das d

dasdas]]	write("Chyba --[[]]--[[ahojkyneee a da das d

dasdas]]pri --[[]]--[[ahojkyneee a da das d

dasdas]]nacitani --[[]]--[[ahojkyneee a da das d

dasdas]]celeho --[[]]--[[ahojkyneee a da das d

dasdas]]cisla!\n")
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]main()
--[[]]--[[ahojkyneee a da das d

dasdas]]