--Should be OK


--[[]]--[[ahojkyneee a da das d

dasdas]]require --[[]]--[[ahojkyneee a da das d

dasdas]]"ifj21"
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]foo(a --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer) --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]return --[[]]--[[ahojkyneee a da das d

dasdas]]a
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]main() --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]local --[[]]--[[ahojkyneee a da das d

dasdas]]a --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]5
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]local --[[]]--[[ahojkyneee a da das d

dasdas]]b --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]number --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]foo(a)
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]a, --[[]]--[[ahojkyneee a da das d

dasdas]]b --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]5, --[[]]--[[ahojkyneee a da das d

dasdas]]88
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]main()
--[[]]--[[ahojkyneee a da das d

dasdas]]