-- Should be OK


--[[]]--[[ahojkyneee a da das d

dasdas]]require --[[]]--[[ahojkyneee a da das d

dasdas]]"ifj21"
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]global --[[]]--[[ahojkyneee a da das d

dasdas]]foo --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]function(integer, --[[]]--[[ahojkyneee a da das d

dasdas]]string, --[[]]--[[ahojkyneee a da das d

dasdas]]number) --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer, --[[]]--[[ahojkyneee a da das d

dasdas]]number, --[[]]--[[ahojkyneee a da das d

dasdas]]integer
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]fuf()
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]fc --[[]]--[[ahojkyneee a da das d

dasdas]](a --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer, --[[]]--[[ahojkyneee a da das d

dasdas]]b --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]number, --[[]]--[[ahojkyneee a da das d

dasdas]]c --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]string)
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]return
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]fuuf()
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]foo(k --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer, --[[]]--[[ahojkyneee a da das d

dasdas]]l --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]string, --[[]]--[[ahojkyneee a da das d

dasdas]]m --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]number) --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]integer, --[[]]--[[ahojkyneee a da das d

dasdas]]number, --[[]]--[[ahojkyneee a da das d

dasdas]]integer
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]return --[[]]--[[ahojkyneee a da das d

dasdas]]0, --[[]]--[[ahojkyneee a da das d

dasdas]]0.1e12222, --[[]]--[[ahojkyneee a da das d

dasdas]]0
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]