-- Program 3: Prace s retezci a vestavenymi funkcemi

require --[[]]--[[ahojkyneee a da das d

dasdas]]"ifj21"
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]function --[[]]--[[ahojkyneee a da das d

dasdas]]main()
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]local --[[]]--[[ahojkyneee a da das d

dasdas]]s1 --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]string --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]"Toto --[[]]--[[ahojkyneee a da das d

dasdas]]je --[[]]--[[ahojkyneee a da das d

dasdas]]nejaky --[[]]--[[ahojkyneee a da das d

dasdas]]text"
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]local --[[]]--[[ahojkyneee a da das d

dasdas]]s2 --[[]]--[[ahojkyneee a da das d

dasdas]]: --[[]]--[[ahojkyneee a da das d

dasdas]]string --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]s1 --[[]]--[[ahojkyneee a da das d

dasdas]].. --[[]]--[[ahojkyneee a da das d

dasdas]]", --[[]]--[[ahojkyneee a da das d

dasdas]]ktery --[[]]--[[ahojkyneee a da das d

dasdas]]jeste --[[]]--[[ahojkyneee a da das d

dasdas]]trochu --[[]]--[[ahojkyneee a da das d

dasdas]]obohatime"
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]write(s1, --[[]]--[[ahojkyneee a da das d

dasdas]]"\010", --[[]]--[[ahojkyneee a da das d

dasdas]]s2)local --[[]]--[[ahojkyneee a da das d

dasdas]]s1len:integer=#s1
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]s1len --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]s1len --[[]]--[[ahojkyneee a da das d

dasdas]]- --[[]]--[[ahojkyneee a da das d

dasdas]]4 --[[]]--[[ahojkyneee a da das d

dasdas]]s1 --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]substr(s2, --[[]]--[[ahojkyneee a da das d

dasdas]]s1len, --[[]]--[[ahojkyneee a da das d

dasdas]]s1len --[[]]--[[ahojkyneee a da das d

dasdas]]+ --[[]]--[[ahojkyneee a da das d

dasdas]]4) --[[]]--[[ahojkyneee a da das d

dasdas]]s1len --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]s1len --[[]]--[[ahojkyneee a da das d

dasdas]]+ --[[]]--[[ahojkyneee a da das d

dasdas]]1
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]write("4 --[[]]--[[ahojkyneee a da das d

dasdas]]znaky --[[]]--[[ahojkyneee a da das d

dasdas]]od", --[[]]--[[ahojkyneee a da das d

dasdas]]s1len, --[[]]--[[ahojkyneee a da das d

dasdas]]". --[[]]--[[ahojkyneee a da das d

dasdas]]znaku --[[]]--[[ahojkyneee a da das d

dasdas]]v --[[]]--[[ahojkyneee a da das d

dasdas]]\"", --[[]]--[[ahojkyneee a da das d

dasdas]]s2, --[[]]--[[ahojkyneee a da das d

dasdas]]"\":", --[[]]--[[ahojkyneee a da das d

dasdas]]s1, --[[]]--[[ahojkyneee a da das d

dasdas]]"\n")
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]write("Zadejte --[[]]--[[ahojkyneee a da das d

dasdas]]serazenou --[[]]--[[ahojkyneee a da das d

dasdas]]posloupnost --[[]]--[[ahojkyneee a da das d

dasdas]]vsech --[[]]--[[ahojkyneee a da das d

dasdas]]malych --[[]]--[[ahojkyneee a da das d

dasdas]]pismen --[[]]--[[ahojkyneee a da das d

dasdas]]a-h, --[[]]--[[ahojkyneee a da das d

dasdas]]")
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]	write("pricemz --[[]]--[[ahojkyneee a da das d

dasdas]]se --[[]]--[[ahojkyneee a da das d

dasdas]]pismena --[[]]--[[ahojkyneee a da das d

dasdas]]nesmeji --[[]]--[[ahojkyneee a da das d

dasdas]]v --[[]]--[[ahojkyneee a da das d

dasdas]]posloupnosti --[[]]--[[ahojkyneee a da das d

dasdas]]opakovat: --[[]]--[[ahojkyneee a da das d

dasdas]]")
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]s1 --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]reads()
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]if --[[]]--[[ahojkyneee a da das d

dasdas]]s1 --[[]]--[[ahojkyneee a da das d

dasdas]]~= --[[]]--[[ahojkyneee a da das d

dasdas]]nil --[[]]--[[ahojkyneee a da das d

dasdas]]then
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]while --[[]]--[[ahojkyneee a da das d

dasdas]]s1 --[[]]--[[ahojkyneee a da das d

dasdas]]~= --[[]]--[[ahojkyneee a da das d

dasdas]]"abcdefgh" --[[]]--[[ahojkyneee a da das d

dasdas]]do
--[[]]--[[ahojkyneee a da das d

dasdas]]	write("\n", --[[]]--[[ahojkyneee a da das d

dasdas]]"Spatne --[[]]--[[ahojkyneee a da das d

dasdas]]zadana --[[]]--[[ahojkyneee a da das d

dasdas]]posloupnost, --[[]]--[[ahojkyneee a da das d

dasdas]]zkuste --[[]]--[[ahojkyneee a da das d

dasdas]]znovu:")
--[[]]--[[ahojkyneee a da das d

dasdas]]	s1 --[[]]--[[ahojkyneee a da das d

dasdas]]= --[[]]--[[ahojkyneee a da das d

dasdas]]reads()
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]else
--[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]] --[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]end
--[[]]--[[ahojkyneee a da das d

dasdas]]
--[[]]--[[ahojkyneee a da das d

dasdas]]main()
--[[]]--[[ahojkyneee a da das d

dasdas]]